System check identified some issues:

WARNINGS:
loan.BranchData.branch_code: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.Customer.loan_account_number: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerHome.pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerOffice.office_pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
Traceback (most recent call last):
  File "E:\Projects\Web dev\django\Tasks\django-authentication\loan\management\commands\upload_loan_data_via_csv.py", line 39, in main_task
    customer_instance = Customer.objects.get(
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
loan.models.DoesNotExist: Customer matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.DataError: (1264, "Out of range value for column 'loan_account_number' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Projects\Web dev\django\Tasks\django-authentication\manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\loan\management\commands\upload_loan_data_via_csv.py", line 139, in handle
    self.main_task()
  File "E:\Projects\Web dev\django\Tasks\django-authentication\loan\management\commands\upload_loan_data_via_csv.py", line 54, in main_task
    customer_instance.save()
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\models\base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\models\base.py", line 763, in save_base
    updated = self._save_table(
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\models\base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\models\base.py", line 906, in _do_insert
    return manager._insert(
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "E:\Projects\Web dev\django\Tasks\django-authentication\pyenv\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.DataError: (1264, "Out of range value for column 'loan_account_number' at row 1")
System check identified some issues:

WARNINGS:
loan.BranchData.branch_code: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.Customer.loan_account_number: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerHome.pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerOffice.office_pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
System check identified some issues:

WARNINGS:
loan.BranchData.branch_code: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.Customer.loan_account_number: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerHome.pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerOffice.office_pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
System check identified some issues:

WARNINGS:
loan.BranchData.branch_code: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.Customer.loan_account_number: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerHome.pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerOffice.office_pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
System check identified some issues:

WARNINGS:
loan.BranchData.branch_code: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.Customer.loan_account_number: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerHome.pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerOffice.office_pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
System check identified some issues:

WARNINGS:
loan.BranchData.branch_code: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.Customer.loan_account_number: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerHome.pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerOffice.office_pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
System check identified some issues:

WARNINGS:
loan.BranchData.branch_code: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.Customer.loan_account_number: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerHome.pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerOffice.office_pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
System check identified some issues:

WARNINGS:
loan.BranchData.branch_code: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.Customer.loan_account_number: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerHome.pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
loan.CustomerOffice.office_pincode: (fields.W122) 'max_length' is ignored when used with PositiveIntegerField.
	HINT: Remove 'max_length' from field
